-- Criação da tabela de tratativas de prospecção
CREATE TABLE TESTE..TRATATIVAS_PROSPECAO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_EVENTO VARCHAR(50) NOT NULL,
    ID_USER VARCHAR(50) NOT NULL,
    NOME_USER VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    TRATADO BIT NOT NULL DEFAULT 0,
    DESCRICAO TEXT,
    DT_AGENDA DATETIME NOT NULL,
    DT_TRATATIVA DATETIME NOT NULL DEFAULT GETDATE(),
    DATA_CRIACAO DATETIME NOT NULL DEFAULT GETDATE(),
    DATA_ATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE()
);

-- Atualização da tabela TRATADAS_HOTLIST
ALTER TABLE TESTE..TRATADAS_HOTLIST
ADD
    data_visita DATETIME NOT NULL DEFAULT GETDATE(),
    tem_perfil_comercial BIT NOT NULL DEFAULT 0,
    motivo_sem_perfil TEXT NULL,
    aceitou_proposta BIT NULL,
    motivo_nao_efetivacao TEXT NULL;

-- Adicionar índices para melhor performance
CREATE INDEX IX_TRATADAS_HOTLIST_data_visita ON TESTE..TRATADAS_HOTLIST(data_visita);
CREATE INDEX IX_TRATADAS_HOTLIST_tem_perfil_comercial ON TESTE..TRATADAS_HOTLIST(tem_perfil_comercial);
CREATE INDEX IX_TRATADAS_HOTLIST_aceitou_proposta ON TESTE..TRATADAS_HOTLIST(aceitou_proposta);
