CREATE TABLE TESTE..HOTLIST (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    supervisor_id UNIQUEIDENTIFIER NOT NULL,
    CNPJ VARCHAR(20),
    NOME_LOJA VARCHAR(255),
    LOCALIZACAO VARCHAR(255),
    AGENCIA VARCHAR(20),
    MERCADO VARCHAR(100),
    PRACA_PRESENCA VARCHAR(3),
    situacao VARCHAR(11),
    DIRETORIA_REGIONAL VARCHAR(255),
    GERENCIA_REGIONAL VARCHAR(255),
    PA VARCHAR(20),
    GERENTE_PJ VARCHAR(255),
    CONSTRAINT FK_HOTLIST_SUPERVISOR FOREIGN KEY (supervisor_id) REFERENCES TESTE..USERS(id)
); 