-- Criação da tabela USER_LOGS
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'USER_LOGS' AND schema_id = SCHEMA_ID('teste'))
BEGIN
    CREATE TABLE teste..USER_LOGS (
        ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        USER_ID UNIQUEIDENTIFIER NOT NULL,
        TIMESTAMP DATETIME DEFAULT GETDATE(),
        ACTION_TYPE NVARCHAR(50) NOT NULL,  -- 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGE', etc
        IP_ADDRESS NVARCHAR(45),  -- IPv4 ou IPv6
        USER_AGENT NVARCHAR(500),  -- Informações do navegador/dispositivo
        DETAILS NVARCHAR(MAX),  -- Detalhes adicionais em JSON
        STATUS NVARCHAR(20) NOT NULL,  -- 'SUCCESS', 'FAILURE', 'WARNING'
        FOREIGN KEY (USER_ID) REFERENCES teste..users(id)
    );

    CREATE INDEX IX_USER_LOGS_TIMESTAMP ON teste..USER_LOGS(TIMESTAMP);
    CREATE INDEX IX_USER_LOGS_USER_ID ON teste..USER_LOGS(USER_ID);
    CREATE INDEX IX_USER_LOGS_ACTION_TYPE ON teste..USER_LOGS(ACTION_TYPE);

    PRINT 'Tabela USER_LOGS criada com sucesso.';
END
ELSE
BEGIN
    PRINT 'A tabela USER_LOGS já existe.';
END 