-- Criação da tabela de tratativas de prospecção
CREATE TABLE TESTE..TRATATIVAS_PROSPECAO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_EVENTO VARCHAR(50) NOT NULL,
    ID_USER VARCHAR(50) NOT NULL,
    NOME_USER VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    TRATADO BIT NOT NULL DEFAULT 0,
    DESCRICAO TEXT,
    DT_AGENDA DATETIME NOT NULL,
    DT_TRATATIVA DATETIME NOT NULL DEFAULT GETDATE(),
    DATA_CRIACAO DATETIME NOT NULL DEFAULT GETDATE(),
    DATA_ATUALIZACAO DATETIME NOT NULL DEFAULT GETDATE()
);
